name: weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

  dio: ^4.0.6
  json_annotation: ^4.4.0
  geolocator: ^8.2.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter: 
  uses-material-design: true

